jwt:
  secretKey: SecretKeyasdfasdfaefawegawegaegaegaegaegeawgaegaerga
  refreshKey: SecretKeyasdfasdfaefawegawegaegdafdgegrhrtj

server:
  address: localhost
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reviewus?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: reviewus
    password: diddiddid123
jpa:
  database: mysql
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      format_sql: true

